use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'NFAPayUtil_Example' do
  pod 'NFAPayUtil', :path => '../'

  target 'NFAPayUtil_Tests' do
    inherit! :search_paths

    
  end
end
